#!/bin/bash
TEST_DIR="test"

pieces=(pond rook knight bishop queen king)

for piece in "${pieces[@]}"
do
  FILE="./test/test_$piece.py"
  if [ -f "$FILE" ]; then
    ASCII_ART="./ascii-art/$piece.txt"
    echo "RUNNING TEST FOR THE FOLLOWING PIECE: $piece"
    cat $ASCII_ART
    echo
    python -m unittest ${TEST_DIR}.test_${piece}
  fi
done
